services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dynamic_web_systems
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend
    volumes:
      - .:/backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - dynamic_web_systems

  migrate:
    image: backend
    command: python manage.py migrate
    depends_on:
      - backend
    networks:
      - dynamic_web_systems

volumes:
  mysql_data:

networks:
  dynamic_web_systems:
