services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    container_name: django_backend
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data:
